# Generated CI/CD Pipeline YAML
# This YAML is compatible with GitHub Actions

# Pipeline: tutorial_pipeline
name: tutorial_pipeline

on:
  push:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
            - name: unnamed_command
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                         python-version: '3.9'
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run tests
              run: pytest || true
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
            - name: unnamed_command
              uses: actions/checkout@v4
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                        heroku_app_name: "your-app-name-here"
    needs: ["build_test"]
